### ISSUE TITLE
An exception of type ConnectionError occurred, arguments: ('Connection aborted.', error(111, 'Connection refused'))

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#481]
Other error, please help, something missed

**Comment by johnfelipe** [comment]
Traceback (most recent call last):
	  File "/home/felipe/sayit/sayit.mysociety.org/manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
	Traceback (most recent call last):
	  File "./scrape.py", line 376, in <module>
		utility.execute()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
		scrape(url)
	  File "./scrape.py", line 367, in scrape
		self.fetch_command(subcommand).run_from_argv(self.argv)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
		call(base_dir+'/manage.py load_akomantoso --file=/home/felipe/actas-consejo-medellin/actas-xml/'+xmlName+' --instance=concejodemedellin --commit', shell=True);
	  File "/usr/lib/python2.7/subprocess.py", line 522, in call
		commands = get_commands()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
		return Popen(*popenargs, **kwargs).wait()
	  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
		apps = settings.INSTALLED_APPS
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
		self._setup(name)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/conf/__init__.py", line 50, in _setup
		self._configure_logging()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/conf/__init__.py", line 72, in _configure_logging
		from django.utils.log import DEFAULT_LOGGING
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/utils/log.py", line 7, in <module>
		pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
		from django.views.debug import ExceptionReporter, get_exception_reporter_filter
	  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/views/debug.py", line 10, in <module>
		from django.http import (HttpResponse, HttpResponseServerError,
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/http/__init__.py", line 2, in <module>
			from django.http.request import (HttpRequest, QueryDict, UnreadablePostError,
	return func(*args)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/http/request.py", line 14, in <module>
		from django.http.multipartparser import MultiPartParser
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/http/multipartparser.py", line 18, in <module>
	KeyboardInterrupt
		from django.utils.text import unescape_entities
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/utils/text.py", line 25, in <module>
		re_words = re.compile(r'&.*?;|<.*?>|(\w[\w-]*)', re.U|re.S)
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/re.py", line 190, in compile
		return _compile(pattern, flags)
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/re.py", line 242, in _compile
		p = sre_compile.compile(pattern, flags)
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/sre_compile.py", line 498, in compile
		p = sre_parse.parse(p, flags)
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/sre_parse.py", line 687, in parse
		tail = source.get()
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/sre_parse.py", line 203, in get
		self.__next()
	  File "/home/felipe/sayit/virtualenv-sayit/lib/python2.7/sre_parse.py", line 183, in __next
		if self.index >= len(self.string):

**Comment by dracos** [comment]
Nothing to do with sayit, 'scrape.py' is not a script in our repo. It sounds like it's taking too long to run and a connection is timing out.
