### ISSUE TITLE
Issue akomantoso 08/2015

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#501]
An exception of type Exception occurred, arguments:
	TLCPerson '/ontology/person/127.0.0.1/' is missing showAs
	Traceback (most recent call last):
	  File "/home/felipe/sayit/virtualenv-sayit/src/django-sayit/speeches/management/import_commands.py", line 120, in import_document
		importer.import_document(path)
	  File "/home/felipe/sayit/virtualenv-sayit/src/django-sayit/speeches/importers/import_akomantoso.py", line 25, in import_document
		return self.parse_document()
	  File "/home/felipe/sayit/virtualenv-sayit/src/django-sayit/speeches/importers/import_akomantoso.py", line 49, in parse_document
		raise Exception("TLCPerson '%s' is missing showAs" % href)
	Exception: TLCPerson '/ontology/person/127.0.0.1/' is missing showAs

For this xml: https://gist.github.com/johnfelipe/9c3db983292785b4ef0c

**Comment by dracos** [comment]
Your source XML has `<TLCPerson href="/ontology/person/127.0.0.1/" id="" showAs="" />` which isn't valid, presumably whatever is generating your XML should not generate an empty person like that.
