### ISSUE TITLE
Installation error today

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#514]
https://github.com/mysociety/sayit.mysociety.org/issues/94

I update django to 1.8, my pip freeze:

	(virtualenv-sayit) felipe@ACTASINTELIGENTES:~/sayit/sayit.mysociety.org$ pip freeze
	audioread==2.1.2
	beautifulsoup4==4.4.1
	bleach==1.4.2
	cffi==1.5.2
	cryptography==1.3.1
	dj-database-url==0.4.0
	Django==1.8.12
	django-allauth==0.16.1
	django-apptemplates==0.0.1
	django-bleach==0.3.0
	django-haystack==2.4.1
	django-model-utils==2.4
	django-pipeline==1.3.27
	django-pipeline-compass-rubygem==0.1.8
	-e git+https://github.com/mysociety/sayit@84f4c451ba428e8aaefc136c094cf57be074942f#egg=django_sayit
	Django-Select2==4.3.2
	django-subdomain-instances==1.0
	django-tastypie==0.13.3
	easy-thumbnails==2.3
	elasticsearch==2.3.0
	enum34==1.1.2
	futures==3.0.5
	html5lib==0.9999999
	idna==2.1
	ipaddress==1.0.16
	mysociety-django-popolo==0.0.5
	mysociety-django-sluggable==0.2.7
	ndg-httpsclient==0.3.2
	oauthlib==1.0.3
	Pillow==3.2.0
	popit-django==0.0.3
	psycopg2==2.5.5
	pyasn1==0.1.7
	pycparser==2.14
	pyOpenSSL==0.14
	python-dateutil==2.5.2
	python-memcached==1.57
	python-mimeparse==1.5.1
	python-openid==2.2.5
	pytz==2016.3
	PyYAML==3.11
	requests==2.9.1
	requests-cache==0.4.12
	requests-oauthlib==0.6.1
	simplejson==3.8.2
	six==1.10.0
	slumber==0.7.1
	South==1.0
	unicode-slugify==0.1.1
	urllib3==1.14

when ./manage.py syncdb

i have this error:

	(virtualenv-sayit) felipe@ACTASINTELIGENTES:~/sayit/sayit.mysociety.org$ ./manage.py syncdb
	Traceback (most recent call last):
	  File "./manage.py", line 10, in <module>
		execute_from_command_line(sys.argv)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
		utility.execute()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
		django.setup()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
		apps.populate(settings.INSTALLED_APPS)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
		app_config.ready()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
		self.module.autodiscover()
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
		autodiscover_modules('admin', register_to=site)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
		import_module('%s.%s' % (app_config.name, module_to_search))
	  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
		__import__(name)
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/allauth/socialaccount/admin.py", line 12, in <module>
		class SocialAppForm(forms.ModelForm):
	  File "/home/felipe/sayit/virtualenv-sayit/local/lib/python2.7/site-packages/django/forms/models.py", line 274, in __new__
		"needs updating." % name
	django.core.exceptions.ImproperlyConfigured: Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is prohibited; form SocialAppForm needs updating.

How solved please

**Comment by dracos** [comment]
This issue is already opened in the other repo.

**Comment by johnfelipe** [comment]
Error is different, but answer me when u wish
